language: node_js

node_js:
- "4"

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  directories:
  - node_modules

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

script:
  - npm run test
  - npm run lint

after_script: "cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
